name: CI/CD

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      website: ${{ steps.filter.outputs.website }}
      lambda: ${{ steps.filter.outputs.lambda }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infra/**'

            website:
              - 'website/**'

            lambda:
              - 'api/**'


  validate:
    needs: changes

    if: needs.changes.outputs.infra == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Format Check
        working-directory: infra
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate


  apply:
    needs:
      - changes
      - validate

    concurrency:
      group: terraform-apply
      cancel-in-progress: false

    if: |
      github.ref == 'refs/heads/main' &&
      needs.changes.outputs.infra == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Build Lambda layer
        run: |
          rm -rf dist/layer_build
          mkdir -p dist/layer_build/python
          
          pip3 install \
          -r api/requirements.txt \
          -t dist/layer_build/python \
          --python-version 3.14 \
          --platform manylinux2014_x86_64 \
          --only-binary=:all:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        env:
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
          TF_VAR_create_api_domain: ${{ secrets.CREATE_API_DOMAIN }}
        run: terraform apply -auto-approve


  website:
    needs: changes

    if: |
      github.ref == 'refs/heads/main' &&
      needs.changes.outputs.website == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy website
        run: |
          aws s3 sync website/ s3://${{ secrets.WEBSITE_BUCKET }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"
          

  lambda:
    needs: changes

    if: |
      github.ref == 'refs/heads/main' &&
      needs.changes.outputs.lambda == 'true'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Build Lambda packages
        run: |
          cd api

          zip ../dist/get_all_posts.zip get_all_posts.py
          zip ../dist/put_post.zip put_post.py
          zip ../dist/delete_post.zip delete_post.py

          cd ..

      - name: Update get_all_posts
        run: |
          aws lambda update-function-code \
            --function-name "get_all_posts" \
            --zip-file fileb://dist/get_all_posts.zip

      - name: Update put_post
        run: |
          aws lambda update-function-code \
            --function-name "put_post" \
            --zip-file fileb://dist/put_post.zip

      - name: Update delete_post
        run: |
          aws lambda update-function-code \
            --function-name "delete_post" \
            --zip-file fileb://dist/delete_post.zip